### ISSUE TITLE
Support newer versions of ESLint

### ISSUE THREAD

**Issue by ghost** [angelozerr/tern-eslint#15]
Hello,

Newer versions of ESLint are not compatible with this plugin. It should be updated.

**Comment by angelozerr** [comment]
Any par are welcome nous time to do that

**Comment by nostalic** [comment]
Thanks for merging #16 @angelozerr ! 
Can we publish it as v0.5.0 on npm? 

 I'll be looking at upgrading to eslint v4.5 next - but this will take a bit longer as there is more refactoring involved ( https://eslint.org/docs/user-guide/migrating-to-4.0.0#breaking-changes-for-integration-developers ).

**Comment by angelozerr** [comment]
Thanks @nostalic for your contribution! tern-eslint 0.5 is now published.
