### ISSUE TITLE
ignores .eslintrc

### ISSUE THREAD

**Issue by letmaik** [angelozerr/tern-eslint#6]
The .eslintrc file can be used to configure some aspects of eslint further, like telling it that the code will run in the browser:

``` js
{
  "env": {
    "browser": 1
  }
}
```

Then it will assume that XMLHttpRequest exists etc.

However, tern-eslint doesn't seem to work in a way such that this file can be used. I assume it is because the file content is given to eslint as a string, not a filename or something else. Still, maybe there's a way to tell eslint the root location so that it has a chance to find the .eslintrc file.

**Comment by angelozerr** [comment]
You can configure tern-eslint with a eslint.json config file by setting the file path of the eslint.json. I'm sorry, I don't understand your requirement?

**Comment by letmaik** [comment]
I think the .eslinerc is typically a file that is read in addition by eslint if it is found, but you are right, you can include those things also directly in the eslint.json as a workaround. Closing this since it's not worth the effort.
