### ISSUE TITLE
Which version of eslint for tern-eslint

### ISSUE THREAD

**Issue by ptitgraig** [angelozerr/tern-eslint#8]
Hello Angelozerr. 
Thanks for bringing this plugin to the community.

I would like to use it in Eclipse for my JS project. I wanted to know which version of eslint is being used ?
I've defined rules for my company that fits Eslint 1.0.0.

Regards

**Comment by angelozerr** [comment]
You can see the version of eslint at https://github.com/angelozerr/tern-eslint/blob/master/package.json#L17

**Comment by ptitgraig** [comment]
Thanks Angelo!
